"""add_audit_logs

Revision ID: 744de3c4a850
Revises: b6163bffa521
Create Date: 2026-03-05 16:16:07.496126

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '744de3c4a850'
down_revision = 'b6163bffa521'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_logs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.Column('room_id', sa.Uuid(), nullable=True),
    sa.Column('tool_name', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('tool_input', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('tool_result', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('agent_name', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
    sa.Column('model', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_created_at'), 'audit_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_audit_logs_room_id'), 'audit_logs', ['room_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_tool_name'), 'audit_logs', ['tool_name'], unique=False)
    op.create_index(op.f('ix_audit_logs_user_id'), 'audit_logs', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_audit_logs_user_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_tool_name'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_room_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_created_at'), table_name='audit_logs')
    op.drop_table('audit_logs')
    # ### end Alembic commands ###
