"""add_reminders

Revision ID: b6163bffa521
Revises: def143549f1d
Create Date: 2026-03-05 15:07:52.812197

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'b6163bffa521'
down_revision = 'def143549f1d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reminders',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('room_id', sa.Uuid(), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=False),
    sa.Column('message', sqlmodel.sql.sqltypes.AutoString(length=1000), nullable=False),
    sa.Column('fire_at', sa.DateTime(), nullable=False),
    sa.Column('recurrence', sa.Enum('ONCE', 'DAILY', 'WEEKLY', name='reminderrecurrence'), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'FIRED', 'CANCELLED', name='reminderstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['chat_users.id'], ),
    sa.ForeignKeyConstraint(['room_id'], ['chat_rooms.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reminders_fire_at'), 'reminders', ['fire_at'], unique=False)
    op.create_index(op.f('ix_reminders_room_id'), 'reminders', ['room_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_reminders_room_id'), table_name='reminders')
    op.drop_index(op.f('ix_reminders_fire_at'), table_name='reminders')
    op.drop_table('reminders')
    # ### end Alembic commands ###
