/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WorkstationRouteImport } from './routes/workstation'
import { Route as SparkbudWebmakerRouteImport } from './routes/sparkbud-webmaker'
import { Route as SparkbudResearchRouteImport } from './routes/sparkbud-research'
import { Route as SparkbudBuilderRouteImport } from './routes/sparkbud-builder'
import { Route as SparkbudAutomationRouteImport } from './routes/sparkbud-automation'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as RecoverPasswordRouteImport } from './routes/recover-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DmRouteImport } from './routes/dm'
import { Route as ControlsRouteImport } from './routes/controls'
import { Route as CommandCenterRouteImport } from './routes/command-center'
import { Route as LayoutRouteImport } from './routes/_layout'
import { Route as LayoutIndexRouteImport } from './routes/_layout/index'
import { Route as MeetingRoomIdRouteImport } from './routes/meeting.$roomId'
import { Route as LayoutSpineRouteImport } from './routes/_layout/spine'
import { Route as LayoutSettingsRouteImport } from './routes/_layout/settings'
import { Route as LayoutItemsRouteImport } from './routes/_layout/items'
import { Route as LayoutChatRouteImport } from './routes/_layout/chat'
import { Route as LayoutAdminRouteImport } from './routes/_layout/admin'

const WorkstationRoute = WorkstationRouteImport.update({
  id: '/workstation',
  path: '/workstation',
  getParentRoute: () => rootRouteImport,
} as any)
const SparkbudWebmakerRoute = SparkbudWebmakerRouteImport.update({
  id: '/sparkbud-webmaker',
  path: '/sparkbud-webmaker',
  getParentRoute: () => rootRouteImport,
} as any)
const SparkbudResearchRoute = SparkbudResearchRouteImport.update({
  id: '/sparkbud-research',
  path: '/sparkbud-research',
  getParentRoute: () => rootRouteImport,
} as any)
const SparkbudBuilderRoute = SparkbudBuilderRouteImport.update({
  id: '/sparkbud-builder',
  path: '/sparkbud-builder',
  getParentRoute: () => rootRouteImport,
} as any)
const SparkbudAutomationRoute = SparkbudAutomationRouteImport.update({
  id: '/sparkbud-automation',
  path: '/sparkbud-automation',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RecoverPasswordRoute = RecoverPasswordRouteImport.update({
  id: '/recover-password',
  path: '/recover-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DmRoute = DmRouteImport.update({
  id: '/dm',
  path: '/dm',
  getParentRoute: () => rootRouteImport,
} as any)
const ControlsRoute = ControlsRouteImport.update({
  id: '/controls',
  path: '/controls',
  getParentRoute: () => rootRouteImport,
} as any)
const CommandCenterRoute = CommandCenterRouteImport.update({
  id: '/command-center',
  path: '/command-center',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutRoute = LayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutIndexRoute = LayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LayoutRoute,
} as any)
const MeetingRoomIdRoute = MeetingRoomIdRouteImport.update({
  id: '/meeting/$roomId',
  path: '/meeting/$roomId',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutSpineRoute = LayoutSpineRouteImport.update({
  id: '/spine',
  path: '/spine',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutSettingsRoute = LayoutSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutItemsRoute = LayoutItemsRouteImport.update({
  id: '/items',
  path: '/items',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutChatRoute = LayoutChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutAdminRoute = LayoutAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => LayoutRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof LayoutIndexRoute
  '/command-center': typeof CommandCenterRoute
  '/controls': typeof ControlsRoute
  '/dm': typeof DmRoute
  '/login': typeof LoginRoute
  '/recover-password': typeof RecoverPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/sparkbud-automation': typeof SparkbudAutomationRoute
  '/sparkbud-builder': typeof SparkbudBuilderRoute
  '/sparkbud-research': typeof SparkbudResearchRoute
  '/sparkbud-webmaker': typeof SparkbudWebmakerRoute
  '/workstation': typeof WorkstationRoute
  '/admin': typeof LayoutAdminRoute
  '/chat': typeof LayoutChatRoute
  '/items': typeof LayoutItemsRoute
  '/settings': typeof LayoutSettingsRoute
  '/spine': typeof LayoutSpineRoute
  '/meeting/$roomId': typeof MeetingRoomIdRoute
}
export interface FileRoutesByTo {
  '/command-center': typeof CommandCenterRoute
  '/controls': typeof ControlsRoute
  '/dm': typeof DmRoute
  '/login': typeof LoginRoute
  '/recover-password': typeof RecoverPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/sparkbud-automation': typeof SparkbudAutomationRoute
  '/sparkbud-builder': typeof SparkbudBuilderRoute
  '/sparkbud-research': typeof SparkbudResearchRoute
  '/sparkbud-webmaker': typeof SparkbudWebmakerRoute
  '/workstation': typeof WorkstationRoute
  '/admin': typeof LayoutAdminRoute
  '/chat': typeof LayoutChatRoute
  '/items': typeof LayoutItemsRoute
  '/settings': typeof LayoutSettingsRoute
  '/spine': typeof LayoutSpineRoute
  '/meeting/$roomId': typeof MeetingRoomIdRoute
  '/': typeof LayoutIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_layout': typeof LayoutRouteWithChildren
  '/command-center': typeof CommandCenterRoute
  '/controls': typeof ControlsRoute
  '/dm': typeof DmRoute
  '/login': typeof LoginRoute
  '/recover-password': typeof RecoverPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/sparkbud-automation': typeof SparkbudAutomationRoute
  '/sparkbud-builder': typeof SparkbudBuilderRoute
  '/sparkbud-research': typeof SparkbudResearchRoute
  '/sparkbud-webmaker': typeof SparkbudWebmakerRoute
  '/workstation': typeof WorkstationRoute
  '/_layout/admin': typeof LayoutAdminRoute
  '/_layout/chat': typeof LayoutChatRoute
  '/_layout/items': typeof LayoutItemsRoute
  '/_layout/settings': typeof LayoutSettingsRoute
  '/_layout/spine': typeof LayoutSpineRoute
  '/meeting/$roomId': typeof MeetingRoomIdRoute
  '/_layout/': typeof LayoutIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/command-center'
    | '/controls'
    | '/dm'
    | '/login'
    | '/recover-password'
    | '/reset-password'
    | '/signup'
    | '/sparkbud-automation'
    | '/sparkbud-builder'
    | '/sparkbud-research'
    | '/sparkbud-webmaker'
    | '/workstation'
    | '/admin'
    | '/chat'
    | '/items'
    | '/settings'
    | '/spine'
    | '/meeting/$roomId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/command-center'
    | '/controls'
    | '/dm'
    | '/login'
    | '/recover-password'
    | '/reset-password'
    | '/signup'
    | '/sparkbud-automation'
    | '/sparkbud-builder'
    | '/sparkbud-research'
    | '/sparkbud-webmaker'
    | '/workstation'
    | '/admin'
    | '/chat'
    | '/items'
    | '/settings'
    | '/spine'
    | '/meeting/$roomId'
    | '/'
  id:
    | '__root__'
    | '/_layout'
    | '/command-center'
    | '/controls'
    | '/dm'
    | '/login'
    | '/recover-password'
    | '/reset-password'
    | '/signup'
    | '/sparkbud-automation'
    | '/sparkbud-builder'
    | '/sparkbud-research'
    | '/sparkbud-webmaker'
    | '/workstation'
    | '/_layout/admin'
    | '/_layout/chat'
    | '/_layout/items'
    | '/_layout/settings'
    | '/_layout/spine'
    | '/meeting/$roomId'
    | '/_layout/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  LayoutRoute: typeof LayoutRouteWithChildren
  CommandCenterRoute: typeof CommandCenterRoute
  ControlsRoute: typeof ControlsRoute
  DmRoute: typeof DmRoute
  LoginRoute: typeof LoginRoute
  RecoverPasswordRoute: typeof RecoverPasswordRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SignupRoute: typeof SignupRoute
  SparkbudAutomationRoute: typeof SparkbudAutomationRoute
  SparkbudBuilderRoute: typeof SparkbudBuilderRoute
  SparkbudResearchRoute: typeof SparkbudResearchRoute
  SparkbudWebmakerRoute: typeof SparkbudWebmakerRoute
  WorkstationRoute: typeof WorkstationRoute
  MeetingRoomIdRoute: typeof MeetingRoomIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/workstation': {
      id: '/workstation'
      path: '/workstation'
      fullPath: '/workstation'
      preLoaderRoute: typeof WorkstationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sparkbud-webmaker': {
      id: '/sparkbud-webmaker'
      path: '/sparkbud-webmaker'
      fullPath: '/sparkbud-webmaker'
      preLoaderRoute: typeof SparkbudWebmakerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sparkbud-research': {
      id: '/sparkbud-research'
      path: '/sparkbud-research'
      fullPath: '/sparkbud-research'
      preLoaderRoute: typeof SparkbudResearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sparkbud-builder': {
      id: '/sparkbud-builder'
      path: '/sparkbud-builder'
      fullPath: '/sparkbud-builder'
      preLoaderRoute: typeof SparkbudBuilderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sparkbud-automation': {
      id: '/sparkbud-automation'
      path: '/sparkbud-automation'
      fullPath: '/sparkbud-automation'
      preLoaderRoute: typeof SparkbudAutomationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recover-password': {
      id: '/recover-password'
      path: '/recover-password'
      fullPath: '/recover-password'
      preLoaderRoute: typeof RecoverPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dm': {
      id: '/dm'
      path: '/dm'
      fullPath: '/dm'
      preLoaderRoute: typeof DmRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/controls': {
      id: '/controls'
      path: '/controls'
      fullPath: '/controls'
      preLoaderRoute: typeof ControlsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/command-center': {
      id: '/command-center'
      path: '/command-center'
      fullPath: '/command-center'
      preLoaderRoute: typeof CommandCenterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof LayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout/': {
      id: '/_layout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof LayoutIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/meeting/$roomId': {
      id: '/meeting/$roomId'
      path: '/meeting/$roomId'
      fullPath: '/meeting/$roomId'
      preLoaderRoute: typeof MeetingRoomIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout/spine': {
      id: '/_layout/spine'
      path: '/spine'
      fullPath: '/spine'
      preLoaderRoute: typeof LayoutSpineRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/settings': {
      id: '/_layout/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof LayoutSettingsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/items': {
      id: '/_layout/items'
      path: '/items'
      fullPath: '/items'
      preLoaderRoute: typeof LayoutItemsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/chat': {
      id: '/_layout/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof LayoutChatRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/admin': {
      id: '/_layout/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof LayoutAdminRouteImport
      parentRoute: typeof LayoutRoute
    }
  }
}

interface LayoutRouteChildren {
  LayoutAdminRoute: typeof LayoutAdminRoute
  LayoutChatRoute: typeof LayoutChatRoute
  LayoutItemsRoute: typeof LayoutItemsRoute
  LayoutSettingsRoute: typeof LayoutSettingsRoute
  LayoutSpineRoute: typeof LayoutSpineRoute
  LayoutIndexRoute: typeof LayoutIndexRoute
}

const LayoutRouteChildren: LayoutRouteChildren = {
  LayoutAdminRoute: LayoutAdminRoute,
  LayoutChatRoute: LayoutChatRoute,
  LayoutItemsRoute: LayoutItemsRoute,
  LayoutSettingsRoute: LayoutSettingsRoute,
  LayoutSpineRoute: LayoutSpineRoute,
  LayoutIndexRoute: LayoutIndexRoute,
}

const LayoutRouteWithChildren =
  LayoutRoute._addFileChildren(LayoutRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  LayoutRoute: LayoutRouteWithChildren,
  CommandCenterRoute: CommandCenterRoute,
  ControlsRoute: ControlsRoute,
  DmRoute: DmRoute,
  LoginRoute: LoginRoute,
  RecoverPasswordRoute: RecoverPasswordRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SignupRoute: SignupRoute,
  SparkbudAutomationRoute: SparkbudAutomationRoute,
  SparkbudBuilderRoute: SparkbudBuilderRoute,
  SparkbudResearchRoute: SparkbudResearchRoute,
  SparkbudWebmakerRoute: SparkbudWebmakerRoute,
  WorkstationRoute: WorkstationRoute,
  MeetingRoomIdRoute: MeetingRoomIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
